import type { AdapterConfigSchema } from "@paperclipai/adapter-utils";

export function getOpenCodeServerConfigSchema(): AdapterConfigSchema {
  return {
    fields: [
      {
        key: "hostname",
        label: "Server hostname",
        type: "text",
        default: "127.0.0.1",
        hint: "Hostname for the opencode serve instance. Use 127.0.0.1 for local, or an IP/hostname for remote.",
      },
      {
        key: "port",
        label: "Server port",
        type: "number",
        default: 4096,
        hint: "Port for the opencode serve instance.",
      },
      {
        key: "timeoutSec",
        label: "Run timeout (seconds)",
        type: "number",
        default: 300,
        hint: "Maximum wall-clock seconds a run may take before the adapter aborts it as timed out.",
      },
      {
        key: "password",
        label: "Server password",
        type: "text",
        default: "",
        hint: "OPENCODE_SERVER_PASSWORD for HTTP basic auth.",
        meta: { secret: true },
      },
      {
        key: "command",
        label: "OpenCode binary path",
        type: "text",
        default: "opencode",
        hint: "Path to the opencode binary. Defaults to resolving from PATH.",
      },
      {
        key: "mode",
        label: "Server connection mode",
        type: "combobox",
        default: "spawn",
        options: [
          { value: "spawn", label: "spawn — Paperclip starts and owns opencode serve as a child process" },
          { value: "connect", label: "connect — Paperclip polls an existing opencode serve; never spawns" },
        ],
        hint: "Default 'spawn' for local dev. Use 'connect' for remote/Docker servers; auto-promotes to 'connect' when hostname is non-loopback.",
      },
      {
        key: "model",
        label: "Default model",
        type: "combobox",
        default: "opencode-go/deepseek-v4-flash",
        hint: "Default model for agent runs. Can be overridden per-run.",
      },
      {
        key: "cheapModel",
        label: "Cheap model",
        type: "combobox",
        default: "opencode-go/deepseek-v4-flash",
        hint: "Cheaper model for cost-sensitive work. Defaults to opencode-go/deepseek-v4-flash.",
      },
      {
        key: "agent",
        label: "OpenCode agent",
        type: "text",
        default: "build",
        hint: "OpenCode agent to use (e.g. build, plan, or custom agent).",
      },
      {
        key: "steps",
        label: "Max steps",
        type: "number",
        default: 300,
        hint: "Maximum agentic steps per run. 0 = unlimited (native doom_loop guard applies).",
      },
      {
        key: "instructionsFilePath",
        label: "Instructions file",
        type: "text",
        default: "",
        hint: "Absolute path to an AGENTS.md-style instructions bundle. Injected into fresh sessions; skipped on resumed sessions.",
      },
      {
        key: "promptTemplate",
        label: "Prompt template",
        type: "textarea",
        default: "",
        hint: "Optional template text appended to the run prompt. Use as a stable suffix (e.g. reporting format or output contract).",
      },
      {
        key: "agentHomeDir",
        label: "Agent home directory",
        type: "text",
        default: "",
        hint: "Absolute path to the agent's home directory (AGENTS.md, TOOLS.md, and a rules/ folder). Mirrored into the remote container so $AGENT_HOME/rules/... resolves. Defaults to the instructions file's parent.",
      },
      {
        key: "agentHomeRemoteDir",
        label: "Remote agent home directory",
        type: "text",
        default: "/home/opc/agent-home",
        hint: "Remote path AGENT_HOME points at inside the serve container. The instructions bundle is synced here and the shell.env plugin injects AGENT_HOME from it.",
      },
      {
        key: "deployAgentHomePlugin",
        label: "Deploy shell.env plugin",
        type: "toggle",
        default: true,
        hint: "Install/refresh the shell.env plugin (injects AGENT_HOME + run-scoped PAPERCLIP_* env into bash tools) on every remote run.",
      },
      {
        key: "paperclipApiUrl",
        label: "Paperclip API URL",
        type: "text",
        default: "",
        hint: "Board API base URL injected as PAPERCLIP_API_URL so the agent can update issues. Defaults to the Paperclip runtime URL from env.",
      },
      {
        key: "sshHost",
        label: "SSH host",
        type: "text",
        default: "",
        hint: "Tailnet host for the VPS that runs the opencode serve container. Leave empty to disable workspace sync (connect-only mode).",
      },
      {
        key: "sshPort",
        label: "SSH port",
        type: "number",
        default: 2222,
        hint: "SSH port exposed by the serve container (typically 2222 to avoid colliding with host ssh).",
      },
      {
        key: "sshUsername",
        label: "SSH username",
        type: "text",
        default: "",
        hint: "SSH user for workspace sync (key-based auth).",
      },
      {
        key: "sshPrivateKey",
        label: "SSH private key",
        type: "text",
        default: "",
        hint: "Private key content (or reference to a Paperclip secret) used to reach the VPS for workspace sync.",
        meta: { secret: true },
      },
      {
        key: "sshKnownHosts",
        label: "SSH known_hosts",
        type: "textarea",
        default: "",
        hint: "Optional known_hosts content to pin the VPS host key. Leave empty to rely on the default known_hosts.",
      },
      {
        key: "strictHostKeyChecking",
        label: "Strict host key checking",
        type: "toggle",
        default: true,
        hint: "Reject SSH connections with an unverified host key. Disable only for ephemeral test environments.",
      },
      {
        key: "remoteServerCwd",
        label: "Remote server cwd",
        type: "text",
        default: "",
        hint: "Stable working directory the serve process uses on the VPS. Workspace sync targets this path; it must match the container's WORKDIR.",
      },
      {
        key: "cwd",
        label: "Local workspace directory",
        type: "text",
        default: "",
        hint: "Optional override for the local workspace directory used as the sync source. Defaults to the Paperclip execution workspace.",
      },
    ],
  };
}